// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPykQfft_SFFfV9GKkc_CQiRsuQrdRT4o',
    appId: '1:351136545444:web:aa02b185d581b5438b4431',
    messagingSenderId: '351136545444',
    projectId: 'app-mobile-7294d',
    authDomain: 'app-mobile-7294d.firebaseapp.com',
    storageBucket: 'app-mobile-7294d.appspot.com',
    measurementId: 'G-X80QPYQP3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYnwtIRkG5fCvifWgyWqgHNZG1v_m85b4',
    appId: '1:351136545444:android:21f8c12f262dfbea8b4431',
    messagingSenderId: '351136545444',
    projectId: 'app-mobile-7294d',
    storageBucket: 'app-mobile-7294d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_gKYap2zU6VuKejCvOZnIFRT3BCQ4lc',
    appId: '1:351136545444:ios:fe3dda4054d6538b8b4431',
    messagingSenderId: '351136545444',
    projectId: 'app-mobile-7294d',
    storageBucket: 'app-mobile-7294d.appspot.com',
    iosClientId: '351136545444-82283gvhv4bopinnb4dnisf8t4bor80g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_gKYap2zU6VuKejCvOZnIFRT3BCQ4lc',
    appId: '1:351136545444:ios:fe3dda4054d6538b8b4431',
    messagingSenderId: '351136545444',
    projectId: 'app-mobile-7294d',
    storageBucket: 'app-mobile-7294d.appspot.com',
    iosClientId: '351136545444-82283gvhv4bopinnb4dnisf8t4bor80g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
